### ISSUE TITLE
Korrekturen

### ISSUE THREAD

**Issue by jzbor** [silas229/union-affairs#1]
Hi,
Erstmal coole Webseite. Bei dem Saftladen hat man ja inzwischen echt den Überblick verloren. Ich hab allerdings zwei kleine Details gefunden, die nicht so ganz hinkommen. Und zwar beim Spahn: "Datum des Bekanntwerdens: 16.08.2021". Ich gehe mal davon aus, dass das 2020 heißen soll. Außerdem scheint das mit den Masken und seinem Ehemann nicht ganz so dramatisch gewesen seien, wie die Headline klang. [Dieser Artikel](https://meedia.de/2021/03/22/jens-spahns-ehemann-spiegel-bedauert-irrefuehrende-ueberschrift/) ordnet das vllt. etwas besser ein.

**Comment by silas229** [comment]
Alles klar, du schlägst also vor, diesen Punkt zu löschen, richtig?

**Comment by jzbor** [comment]
Ja entweder das, oder den Kontext angeben, erstmal einklammern und schauen, ob da noch was folgt. Aber ich finds so, wies jetzt da steht etwas irrefürend...

**Comment by silas229** [comment]
Fixed in a7fb73766a6601d4c6b01184054e55a8fbecc4a6
